=== ahmed-fahmy17/attendance-management-system/xml/classesSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="IDType">
		<xs:restriction base="xs:string">
		  <xs:pattern value="[0-9]{14}"/>
		</xs:restriction>
	 </xs:simpleType>
	<xs:element name="classes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="class" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="classId" type="xs:string"></xs:element>
							<xs:element name="className" type="xs:string"></xs:element>
							<xs:element name="teacherId" type="IDType"></xs:element>
							<xs:element name="students">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="studentId" type="IDType" maxOccurs="unbounded"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ahmed-fahmy17/attendance-management-system/xml/classes.xml
<?xml version="1.0" encoding="UTF-8"?>
<classes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\iti\projects\c# and XML project\attendance-management-system\xml\classesSchema.xsd">
  <class>
    <classId>Math2</classId>
    <className>Mathematics2</className>
    <teacherId>11144411111215</teacherId>
    <students>
      <studentId>01234532569421</studentId>
    </students>
  </class>
  <class>
    <classId>Math3</classId>
    <className>Mathematics3</className>
    <teacherId>11144411115555</teacherId>
    <students>
      <studentId>01234532569421</studentId>
    </students>
  </class>
</classes>
